Module7 task1
htmlacademy-javascript/668021-keksobooking-21 pull request #10
Opened 2020-10-20 07:35 UTC by SergWulf

2020-10-20 09:06 UTC, 4err requested changes
Функционал фильтрации неплохо бы вынести в отдельный модуль.

2020-10-20 09:06 UTC, 4err commented on js/map.js
> +    window.data.filterRealEstates = window.data.realEstates.filter(function (realEstate) {
Ух какая мешанина всего в этой функции. Она абсолютно нечитабельна. Куча return это тоже не есть хорошо. Разбей ее на маленькие функции, для каждой проверки и используй эти функции. Ну и нужно избавиться от такого количества return.

2020-10-20 09:06 UTC, 4err commented on js/pin.js
> +    }
Прям напрашивается тернарный оператор.

2020-10-21 06:11 UTC, SergWulf commented on js/pin.js
> +    }
Ок, готово!

2020-10-21 09:08 UTC, SergWulf commented on js/map.js
> +    window.data.filterRealEstates = window.data.realEstates.filter(function (realEstate) {
Разбил ее на несколько функций. От множества return избавился булевой переменной.

2020-10-21 10:50 UTC, SergWulf commented on js/map.js
> +    const blockPins = document.querySelector('.map__pins');
Селектор применил, но вот доступ к живой коллекции потерял. Пришлось гуглить решение :)

2020-10-22 05:51 UTC, 4err requested changes

2020-10-22 05:51 UTC, 4err commented on js/filter.js
> +  const featuresValues = formFilters.querySelector('.map__features').querySelectorAll('.map__checkbox');
Почему не заменить на `querySelectorAll('.map__features .map__checkbox');`
Квери селектор затратная функция, поэтому нужно стараться минимизировать ее использование.

2020-10-22 05:51 UTC, 4err commented on js/filter.js
> +    }
А почему опять же не собрать все значения все еще через querySelector используя псевдокласс `:checked`? Так мы сразу получим коллекцию выбранных элементов.

2020-10-22 05:51 UTC, 4err commented on js/filter.js
> +      if (valuesFormFilters.get('price') === 'low') {
Если ты используешь одну переменную для разных условий, то лучше использовать вместо if условие `switch/case`

Ну и тут нет необходимости во вложенных if, если оставлять так, то их можно объединить в один используя оператор логического И

2020-10-22 05:51 UTC, 4err commented on js/filter.js
> +        if (realEstateFeatures.length !== 0) {
Аналогично указанному выше, тут нет необходимости во вложенности, можно объединить в один if

2020-10-22 05:51 UTC, 4err commented on js/filter.js
> +            if ((realEstateFeatures.indexOf(valuesFeatures[i])) === -1) {
В ES6 есть метод `includes()`

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2020-10-22 05:51 UTC, 4err commented on js/filter.js
> +        checkFilterFeatures(realEstate['offer']['features']);
Это все еще очень страшно выглядит :)  Когда я говорил разбить на функции, имел ввиду, что у тебя будет несколько функций, каждая из которых возвращает true/false.
Например, `isHousingType()`, `isPrice`
И метод фильтра получится результатом логической суммы этих функций. 
А всю проверку нужно вынести внутрь этих функций. == `any` и прочее. Гостей и комнаты тоже, в дальнейшем логика может поменяться и если нужно будет измениь ее, нам не придется лезть в фильтр.

2020-10-22 05:51 UTC, 4err commented on js/filter.js
> +  }
Т.к. мы пересчитываем фильтр при любом изменении, нет необходимости вешать обработчики на каждый элемент. Достаточно повесить на форму событие `change`

2020-10-22 06:55 UTC, SergWulf commented on js/filter.js
> +  const featuresValues = formFilters.querySelector('.map__features').querySelectorAll('.map__checkbox');
Ок!

2020-10-22 08:38 UTC, SergWulf commented on js/filter.js
> +    }
Долго искал псевдокласс :selected, а оказывается псевдокласс :checked забирает и те элементы, у которых selected=true. Сейчас буду править.

2020-10-22 13:32 UTC, SergWulf commented on js/filter.js
> +      if (valuesFormFilters.get('price') === 'low') {
Готово!

2020-10-22 14:08 UTC, SergWulf commented on js/filter.js
> +        if (realEstateFeatures.length !== 0) {
Объединил!

2020-10-22 14:08 UTC, SergWulf commented on js/filter.js
> +            if ((realEstateFeatures.indexOf(valuesFeatures[i])) === -1) {
Ок!

2020-10-22 14:10 UTC, SergWulf commented on js/filter.js
> +  }
Ок, убрал лишний код с циклами.

2020-10-22 14:29 UTC, SergWulf commented on js/filter.js
> +        checkFilterFeatures(realEstate['offer']['features']);
Ок!

2020-10-23 05:42 UTC, merged