Подготовка к защите.
htmlacademy-javascript/668021-keksobooking-21 pull request #14
Opened 2020-10-30 11:04 UTC by SergWulf

2020-11-02 06:12 UTC, 4err requested changes
Если после открытия карточки кликнуть в любом месте страницы, то закрытие по ESC не работает.

https://take.ms/6FWWX Здесь и в других модулях. 
1. В именах полей не должно быть имен модуля. В данном случае должно быть просто `render`, а не `renderCard`.
2. В случае одинаковых имен следует использоовать сокращенный синтаксис объектов:
```
window.card = {
  renderCard
};
````

https://take.ms/1CC6k Вот эти 2 объекта лучше объединить в один.

Как-то я пропустил data.js. У тебя получился модуль с кучей констант и параметров.  но таким образом модули сами по себе стали более раздробленными. Нужно все-таки данные относящиеся к конкретным модулям перенести к соответствующим модулям.

https://take.ms/cpAb7 Повторение одного и того же квери селектора несколько раз. Нужно сохранить первый поиск в переменную и работать с ним. Это встречается не только здесь, просмотри везде, где более одного раза используется, нужно вынести в переменную.

https://take.ms/8od0n Тоже как-то пропустил. Все эти параметры можно просто прописать в HTML. Таким образом они будут работать и при отключенном JS. Дефолтные значения также можно прописать в HTML

https://take.ms/d6oHf Имена обработчиков должны быть по форме либо `onДествие`, либо `событиеHandler` Поправь во всех местах.

Для соответствия критерию про использование ES6, в линтере не должно быть warning. Нужно все исправить.

Все циклы, которые возможно, нужно перевести на forEach()

2020-11-05 08:19 UTC, 4err requested changes

2020-11-05 08:19 UTC, 4err commented on js/map.js
> +const URL_DOWNLOAD = `https://21.javascript.pages.academy/keksobooking/data`;
Константы идут до основного кода.

2020-11-05 08:19 UTC, 4err commented on js/map.js
> +  window.load.onData(getData, getError, `GET`, URL_DOWNLOAD);
Лучше не использовать on вне обработчика.

getData и getError это тоже обработчики, которые должны иметь в имени Handler

2020-11-05 09:20 UTC, SergWulf commented on js/map.js
> +const URL_DOWNLOAD = `https://21.javascript.pages.academy/keksobooking/data`;
Ок, поднимаю выше!

2020-11-05 10:34 UTC, merged